qq

diff --git a/mac b/mac
--- a/mac
+++ b/mac
@@ -55,55 +55,6 @@ fancy_echo "updating all of the OS X packages – get you up to date with Apple.
 
   sudo softwareupdate -i -a
 
-fancy_echo "
-###############################################################################
-# zsh shell installation                                                      #
-###############################################################################
-"
-
-append_to_zshrc() {
-  local text="$1" zshrc
-  local skip_new_line="$2"
-
-  if [[ -w "$HOME/.zshrc.local" ]]; then
-    zshrc="$HOME/.zshrc.local"
-  else
-    zshrc="$HOME/.zshrc"
-  fi
-
-  if ! grep -Fqs "$text" "$zshrc"; then
-    if (( skip_new_line )); then
-      printf "%s\n" "$text" >> "$zshrc"
-    else
-      printf "\n%s\n" "$text" >> "$zshrc"
-    fi
-  fi
-}
-
-trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
-
-set -e
-
-if [[ ! -d "$HOME/.bin/" ]]; then
-  mkdir "$HOME/.bin"
-fi
-
-if [ ! -f "$HOME/.zshrc" ]; then
-  touch "$HOME/.zshrc"
-fi
-
-append_to_zshrc 'export PATH="$HOME/.bin:$PATH"'
-
-if [[ "$SHELL" != /usr/local/bin/zsh ]]; then
-  fancy_echo "Changing your shell to homebrew zsh..."
-    if [ ! -e /usr/local/bin/zsh ]; then
-      ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
-      brew install zsh
-    fi
-    echo "/usr/local/bin/zsh" | sudo tee -a /etc/shells
-    chsh -s "/usr/local/bin/zsh"
-    #exec zsh
-fi
 
 ###############################################################################
 # brew & cask helper utils                                                    #
@@ -180,6 +131,7 @@ brew_cask_install_or_upgrade() {
   fi
 }
 
+
 fancy_echo "
 ###############################################################################
 # homebrew & homebrew cask installation                                       #
@@ -224,7 +176,6 @@ fancy_echo "upgrade all homebrew packages ...
 
   brew upgrade
 
-
 # Tap Repos
 brew tap homebrew/dupes
 brew tap homebrew/versions
@@ -232,12 +183,61 @@ brew tap caskroom/cask
 brew tap caskroom/versions
 brew tap caskroom/fonts
 
-
-
 fancy_echo "installing cask for homebrew – extends Homebrew and brings its elegance, simplicity, and speed to OS X applications and large binaries alike: http://caskroom.io/....
 ======================================"
 
   brew_install_or_upgrade 'caskroom/cask/brew-cask'
+
+
+fancy_echo "
+###############################################################################
+# zsh shell installation                                                      #
+###############################################################################
+"
+
+append_to_zshrc() {
+  local text="$1" zshrc
+  local skip_new_line="$2"
+
+  if [[ -w "$HOME/.zshrc.local" ]]; then
+    zshrc="$HOME/.zshrc.local"
+  else
+    zshrc="$HOME/.zshrc"
+  fi
+
+  if ! grep -Fqs "$text" "$zshrc"; then
+    if (( skip_new_line )); then
+      printf "%s\n" "$text" >> "$zshrc"
+    else
+      printf "\n%s\n" "$text" >> "$zshrc"
+    fi
+  fi
+}
+
+trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
+
+set -e
+
+if [[ ! -d "$HOME/.bin/" ]]; then
+  mkdir "$HOME/.bin"
+fi
+
+if [ ! -f "$HOME/.zshrc" ]; then
+  touch "$HOME/.zshrc"
+fi
+
+append_to_zshrc 'export PATH="$HOME/.bin:$PATH"'
+
+if [[ "$SHELL" != /usr/local/bin/zsh ]]; then
+  fancy_echo "Changing your shell to homebrew zsh..."
+    if [ ! -e /usr/local/bin/zsh ]; then
+      #ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+      brew install zsh
+    fi
+    echo "/usr/local/bin/zsh" | sudo tee -a /etc/shells
+    chsh -s "/usr/local/bin/zsh"
+    #exec zsh
+fi
 
 
 fancy_echo "
