organizing

diff --git a/mac b/mac
--- a/mac
+++ b/mac
@@ -14,43 +14,9 @@ fancy_echo() {
   printf "\n%b\n" "$1"
 }
 
-append_to_zshrc() {
-  local text="$1" zshrc
-  local skip_new_line="$2"
-
-  if [[ -w "$HOME/.zshrc.local" ]]; then
-    zshrc="$HOME/.zshrc.local"
-  else
-    zshrc="$HOME/.zshrc"
-  fi
-
-  if ! grep -Fqs "$text" "$zshrc"; then
-    if (( skip_new_line )); then
-      printf "%s\n" "$text" >> "$zshrc"
-    else
-      printf "\n%s\n" "$text" >> "$zshrc"
-    fi
-  fi
-}
-
-trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
-
-set -e
-
-if [[ ! -d "$HOME/.bin/" ]]; then
-  mkdir "$HOME/.bin"
-fi
-
-if [ ! -f "$HOME/.zshrc" ]; then
-  touch "$HOME/.zshrc"
-fi
-
-append_to_zshrc 'export PATH="$HOME/.bin:$PATH"'
-
-if [[ "$SHELL" != */zsh ]]; then
-  fancy_echo "Changing your shell to zsh ..."
-    chsh -s $(which zsh)
-fi
+# ==============================================================================
+# brew & brew-cask stuff
+# ==============================================================================
 
 brew_install_or_upgrade() {
   if brew_is_installed "$1"; then
@@ -132,6 +98,62 @@ brew_cask_install_or_upgrade() {
     brew cask install "$@"
   fi
 }
+
+# ==============================================================================
+# zsh shell stuff
+# ==============================================================================
+
+fancy_echo "Installing zsh ..."
+  brew_install_or_upgrade 'zsh'
+
+fancy_echo "Installing zsh ..."
+  brew_install_or_upgrade 'zsh-completions'
+
+#install oh-my-zsh
+curl -L http://install.ohmyz.sh | sh
+
+
+append_to_zshrc() {
+  local text="$1" zshrc
+  local skip_new_line="$2"
+
+  if [[ -w "$HOME/.zshrc.local" ]]; then
+    zshrc="$HOME/.zshrc.local"
+  else
+    zshrc="$HOME/.zshrc"
+  fi
+
+  if ! grep -Fqs "$text" "$zshrc"; then
+    if (( skip_new_line )); then
+      printf "%s\n" "$text" >> "$zshrc"
+    else
+      printf "\n%s\n" "$text" >> "$zshrc"
+    fi
+  fi
+}
+
+trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
+
+set -e
+
+if [[ ! -d "$HOME/.bin/" ]]; then
+  mkdir "$HOME/.bin"
+fi
+
+if [ ! -f "$HOME/.zshrc" ]; then
+  touch "$HOME/.zshrc"
+fi
+
+append_to_zshrc 'export PATH="$HOME/.bin:$PATH"'
+
+if [[ "$SHELL" != */zsh ]]; then
+  fancy_echo "Changing your shell to zsh ..."
+    chsh -s $(which zsh)
+fi
+
+
+fancy_echo "Installing tmux, to save project state and switch between projects ..."
+brew_install_or_upgrade 'tmux'
 
 # ==============================================================================
 # github dev stuff
@@ -223,6 +245,12 @@ node_version="0.10.33"
 
 fancy_echo "Installing NVM, Node.js, and NPM, for running apps and installing JavaScript packages ..."
   brew_install_or_upgrade 'nvm'
+
+fancy_echo "Installing Node ..."
+  brew_install_or_upgrade 'node'
+
+export NODE_PATH="/usr/local/lib/node"
+export PATH="/usr/local/share/npm/bin:$PATH"
 
 npm install -g mocha
 npm install -g grunt-cli
